---
deployment:
  tasks:
    - export DEPLOYPATH =/home/witbal5/sshakil.com/
    - /bin/cp /public/* $DEPLOYPATH
    - /bin/cp /src/_app.js $DEPLOYPATH
    - /bin cp /src/* $DEPLOYPATH
    - /bin/cp * $DEPLOYPATH